export const EtchelizerPatterns = [
    {name: "Nature", pattern: ['etch-bl-right', 'etch-bl-top', 'etch-br-left', 'etch-br-top', 'etch-main-bottom', 'etch-main-right', 'etch-tl-bottom', 'etch-tr-bottom', 'etch-tr-left', 'etch-tr-top']},
    {name: "Love", pattern: ['etch-bl-left', 'etch-bl-right', 'etch-bl-top', 'etch-br-bottom', 'etch-main-bottom', 'etch-main-top', 'etch-tl-top', 'etch-tr-bottom', 'etch-tr-left', 'etch-tr-right']},
    {name: "Force", pattern: ['etch-bl-left', 'etch-bl-right', 'etch-bl-top', 'etch-main-right', 'etch-main-top', 'etch-tr-top']},
    {name: "Transform", pattern: ['etch-bl-bottom', 'etch-br-bottom', 'etch-main-bottom', 'etch-main-right', 'etch-main-top', 'etch-tl-right', 'etch-tl-top', 'etch-tr-left', 'etch-tr-top']},
    {name: "Change", pattern: ['etch-bl-bottom', 'etch-bl-left', 'etch-bl-right', 'etch-bl-top', 'etch-br-top', 'etch-main-left', 'etch-main-top', 'etch-tl-right', 'etch-tr-bottom', 'etch-tr-left']},
    {name: "Machine", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-br-bottom', 'etch-main-bottom', 'etch-main-left', 'etch-main-top', 'etch-tl-right', 'etch-tl-top', 'etch-tr-top']},
    {name: "Future", pattern: ['etch-bl-bottom', 'etch-bl-left', 'etch-br-bottom', 'etch-br-left', 'etch-br-top', 'etch-main-right', 'etch-main-top', 'etch-tl-top', 'etch-tr-top']},
    {name: "Cycle", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-bl-top', 'etch-main-left', 'etch-main-right', 'etch-main-top']},
    {name: "Merge", pattern: ['etch-bl-left', 'etch-bl-top', 'etch-main-bottom', 'etch-main-left', 'etch-main-right', 'etch-main-top', 'etch-tl-right', 'etch-tl-top']},
    {name: "Dependence", pattern: ['etch-bl-left', 'etch-br-bottom', 'etch-br-left', 'etch-br-right', 'etch-br-top', 'etch-main-left', 'etch-main-top', 'etch-tl-left', 'etch-tl-top', 'etch-tr-top']},
    {name: "Void", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-bl-top', 'etch-main-bottom', 'etch-main-right', 'etch-main-top', 'etch-tl-left']},
    {name: "Energy", pattern: ['etch-bl-bottom', 'etch-bl-left', 'etch-bl-top', 'etch-br-right', 'etch-main-right', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-left', 'etch-tr-right']},
    {name: "Mutual", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-br-left', 'etch-main-left', 'etch-tl-right', 'etch-tr-left', 'etch-tr-top']},
    {name: "Contradict", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-br-right', 'etch-br-top', 'etch-main-bottom', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top']},
    {name: "Power", pattern: ['etch-main-right', 'etch-tl-bottom', 'etch-tl-left', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Possibility", pattern: ['etch-bl-left', 'etch-bl-right', 'etch-bl-top', 'etch-br-bottom', 'etch-main-bottom', 'etch-main-top', 'etch-tl-left', 'etch-tl-top', 'etch-tr-bottom', 'etch-tr-right', 'etch-tr-top']},
    {name: "Encourage", pattern: ['etch-bl-bottom', 'etch-br-bottom', 'etch-br-right', 'etch-main-bottom', 'etch-main-right', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top', 'etch-tr-right']},
    {name: "Convey", pattern: ['etch-bl-left', 'etch-br-bottom', 'etch-br-left', 'etch-main-bottom', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-left', 'etch-tr-right']},
    {name: "Wisdom", pattern: ['etch-bl-left', 'etch-br-bottom', 'etch-br-right', 'etch-main-left', 'etch-main-right', 'etch-tl-left', 'etch-tr-bottom', 'etch-tr-right', 'etch-tr-top']},
    {name: "Dynamic", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-br-right', 'etch-br-top', 'etch-main-bottom', 'etch-main-right', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-left']},
    {name: "Intelligence", pattern: ['etch-bl-bottom', 'etch-bl-left', 'etch-br-left', 'etch-br-right', 'etch-br-top', 'etch-main-top', 'etch-tl-right', 'etch-tl-top', 'etch-tr-right']},
    {name: "Entropy", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-bl-top', 'etch-br-bottom', 'etch-br-left', 'etch-br-right', 'etch-main-bottom', 'etch-main-top', 'etch-tl-left', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Society", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-br-bottom', 'etch-br-left', 'etch-main-bottom', 'etch-main-left', 'etch-main-right', 'etch-main-top', 'etch-tl-right', 'etch-tl-top', 'etch-tr-left', 'etch-tr-top']},
    {name: "Chaos", pattern: ['etch-bl-bottom', 'etch-br-right', 'etch-br-top', 'etch-main-bottom', 'etch-main-top', 'etch-tl-left', 'etch-tr-left', 'etch-tr-right']},
    {name: "Growth", pattern: ['etch-br-left', 'etch-br-right', 'etch-br-top', 'etch-main-bottom', 'etch-main-right', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right']},
    {name: "Civilization", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-br-bottom', 'etch-br-left', 'etch-main-top', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top', 'etch-tr-left', 'etch-tr-right', 'etch-tr-top']},
    {name: "Spur", pattern: ['etch-bl-top', 'etch-br-bottom', 'etch-br-right', 'etch-main-right', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top', 'etch-tr-right']},
    {name: "Infinite", pattern: ['etch-bl-left', 'etch-main-bottom', 'etch-main-right', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top', 'etch-tr-top']},
    {name: "Motion", pattern: ['etch-bl-left', 'etch-bl-top', 'etch-main-bottom', 'etch-main-left', 'etch-tl-right', 'etch-tl-top', 'etch-tr-right']},
    {name: "Harmony", pattern: ['etch-bl-left', 'etch-bl-top', 'etch-br-bottom', 'etch-br-left', 'etch-main-left', 'etch-main-right', 'etch-tl-right', 'etch-tl-top', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Resurrect", pattern: ['etch-bl-left', 'etch-br-bottom', 'etch-br-left', 'etch-br-right', 'etch-br-top', 'etch-main-left', 'etch-main-right', 'etch-tl-left', 'etch-tr-right', 'etch-tr-top']},
    {name: "Weave", pattern: ['etch-br-bottom', 'etch-br-right', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top', 'etch-tr-bottom', 'etch-tr-top']},
    {name: "Rebirth", pattern: ['etch-bl-left', 'etch-bl-right', 'etch-bl-top', 'etch-br-bottom', 'etch-main-bottom', 'etch-main-right', 'etch-main-top', 'etch-tl-left', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Control", pattern: ['etch-bl-left', 'etch-br-right', 'etch-main-bottom', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-left', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Sacrifice", pattern: ['etch-bl-left', 'etch-bl-right', 'etch-br-bottom', 'etch-br-left', 'etch-main-left', 'etch-main-right', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Time", pattern: ['etch-bl-left', 'etch-br-right', 'etch-br-top', 'etch-main-left', 'etch-main-right', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top']},
    {name: "Constraint", pattern: ['etch-br-right', 'etch-main-bottom', 'etch-main-right', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-top', 'etch-tr-left', 'etch-tr-right']},
    {name: "Inhibit", pattern: ['etch-bl-bottom', 'etch-bl-left', 'etch-br-left', 'etch-br-top', 'etch-tl-left', 'etch-tl-top', 'etch-tr-bottom', 'etch-tr-left']},
    {name: "Creativity", pattern: ['etch-bl-bottom', 'etch-br-bottom', 'etch-br-right', 'etch-br-top', 'etch-main-bottom', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top', 'etch-tr-right', 'etch-tr-top']},
    {name: "Stimulate", pattern: ['etch-br-left', 'etch-br-right', 'etch-br-top', 'etch-main-right', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-right', 'etch-tl-top', 'etch-tr-right', 'etch-tr-top']},
    {name: "Momentum", pattern: ['etch-bl-bottom', 'etch-bl-left', 'etch-bl-right', 'etch-br-right', 'etch-br-top', 'etch-main-bottom', 'etch-main-left', 'etch-tl-left', 'etch-tl-top']},
    {name: "Balance", pattern: ['etch-bl-left', 'etch-bl-top', 'etch-main-bottom', 'etch-main-top', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Resilience", pattern: ['etch-bl-bottom', 'etch-bl-left', 'etch-bl-right', 'etch-bl-top', 'etch-main-bottom', 'etch-main-right', 'etch-tl-left', 'etch-tl-top']},
    {name: "Flow", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-br-right', 'etch-br-top', 'etch-main-left', 'etch-main-top']},
    {name: "Believe", pattern: ['etch-main-bottom', 'etch-main-right', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-top', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Tradition", pattern: ['etch-bl-bottom', 'etch-bl-right', 'etch-br-bottom', 'etch-main-bottom', 'etch-main-left', 'etch-main-top', 'etch-tl-top', 'etch-tr-right', 'etch-tr-top']},
    {name: "Nurture", pattern: ['etch-bl-left', 'etch-br-left', 'etch-br-right', 'etch-br-top', 'etch-main-left', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-right', 'etch-tr-top']},
    {name: "Honor", pattern: ['etch-bl-bottom', 'etch-main-bottom', 'etch-main-top', 'etch-tl-right', 'etch-tl-top', 'etch-tr-bottom', 'etch-tr-right']},
    {name: "Form", pattern: ["etch-bl-top","etch-br-bottom","etch-br-right","etch-main-bottom","etch-main-top","etch-tl-left","etch-tr-bottom","etch-tr-left","etch-tr-right","etch-tr-top"]},
    {name: "Question", pattern: ["etch-bl-left","etch-br-right","etch-main-top","etch-tl-bottom","etch-tl-left","etch-tl-right","etch-tl-top","etch-tr-left"]},
    {name: "Static", pattern: ["etch-br-bottom","etch-br-left","etch-br-right","etch-main-bottom","etch-main-left","etch-main-top","etch-tr-left","etch-tr-top"]},
    {name: "Exist", pattern: ["etch-bl-left","etch-bl-right","etch-bl-top","etch-br-right","etch-main-bottom","etch-main-right","etch-main-top","etch-tl-left","etch-tl-top","etch-tr-right"]},
    {name: "Elevate", pattern: ["etch-bl-left","etch-main-bottom","etch-main-right","etch-tl-bottom","etch-tl-left","etch-tl-right","etch-tl-top","etch-tr-bottom","etch-tr-right"]},
    {name: "Survival", pattern: ["etch-bl-bottom","etch-bl-left","etch-bl-right","etch-bl-top","etch-main-bottom","etch-main-right","etch-tl-left","etch-tr-right","etch-tr-top"]},
    {name: "System", pattern: ["etch-bl-top","etch-br-bottom","etch-br-left","etch-br-top","etch-tl-bottom","etch-tl-right","etch-tl-top","etch-tr-bottom"]},
    {name: "Remember", pattern: ["etch-bl-left","etch-bl-top","etch-br-right","etch-main-bottom","etch-main-top","etch-tl-top"]},
    {name: "Sustain", pattern: ["etch-bl-left","etch-bl-right","etch-bl-top","etch-main-bottom","etch-tl-left","etch-tl-right","etch-tl-top"]},
    {name: "Ethereal", pattern: ["etch-bl-bottom","etch-bl-top","etch-br-bottom","etch-br-right","etch-main-bottom","etch-main-top","etch-tl-left","etch-tl-right","etch-tr-top"]},
    {name: "Discover", pattern: ["etch-bl-top","etch-br-bottom","etch-br-right","etch-br-top","etch-main-right","etch-main-top","etch-tl-bottom","etch-tr-bottom","etch-tr-top"]},
    {name: "Explore", pattern: ["etch-br-right","etch-br-top","etch-main-bottom","etch-tl-left","etch-tl-right","etch-tl-top","etch-tr-top"]},
];

export const AllSides = ['etch-bl-bottom', 'etch-bl-left', 'etch-bl-right', 'etch-bl-top', 'etch-br-bottom', 'etch-br-left', 'etch-br-right', 'etch-br-top', 'etch-main-bottom', 'etch-main-left', 'etch-main-right', 'etch-main-top', 'etch-tl-bottom', 'etch-tl-left', 'etch-tl-right', 'etch-tl-top', 'etch-tr-bottom', 'etch-tr-left', 'etch-tr-right', 'etch-tr-top'];