export const COLOURS = [
    { colour: "red", subShades: ["maroon", "rust", "scarlet"] },
    { colour: "bronze", subShades: ["umber", "cola", "clay"] },
    { colour: "yellow", subShades: ["cider", "mustard", "gold"] },
    { colour: "lime", subShades: ["lime", "lime", "lime"] },
    { colour: "green", subShades: ["ochre", "olive", "clover"] },
    { colour: "jade", subShades: ["moss", "viridian", "fern"] },
    { colour: "teal", subShades: ["cyprus", "turquoise", "cyan"] },
    { colour: "blue", subShades: ["prussian", "cobalt", "aegean"] },
    { colour: "indigo", subShades: ["midnight", "navy", "denim"] },
    { colour: "purple", subShades: ["aubergine", "jam", "amethyst"] },
    { colour: "violet", subShades: ["byzantine", "magenta", "orchid"] },
    { colour: "fuchsia", subShades: ["wine", "cerise", "rose"] },
];

type CharacterColours = {
    [key: string]: string[];
};

export const CHARACTERS_COLOURS: CharacterColours = {
    scarlet: ["Yeshin Laevis"],
    rust: [
        "Cinare Montor",
        "Valtel Gurtea",
        "Sova Amalie",
        "The Annalist",
        "Racren Innali",
        "Cepros Xirong",
    ],
    clay: [
        "Talald Hieron",
        "Dismas Mersiv",
        "The Fomenter",
        "Rodere",
        "Garnie",
        "Husske Mayzee",
    ],
    umber: ["Thesal Voorat", "Degner Veibod"],
    cornsyrup: ["Arcjec Voorat", "Thesal Voorat"],
    gold: [
        "Mshiri Libeta",
        "Vyrmis Sturra",
        "Vellia",
        "Jentha Briati",
        "Mosura Briati",
        "Lipsen Fluxum",
        "Hayyan Refero",
        "Sabine Berare",
    ],
    lime: ["Ellsee Raines", "Zekura Raines"],
    olive: [
        "Sirage Feltri",
        "Mekris",
        "Albion Shukra",
        "Cyprim Shukra",
        "Pascal",
        "Linole Pomace",
        "Aumtzi Maught",
    ],
    ochre: ["Raurou Dersal", "Tenemi Tenbra"],
    viridian: ["Gerbat Batrav", "Cepora", "Glomer Hicner", "Hamifi Hekrix"],
    cyan: ["Turnin Kaikai"],
    turquoise: [
        "Serpaz Helilo",
        "Secily Iopara",
        "Arcamu Iopara",
        "Crytum Lydian",
    ],
    cyprus: ["Aislin", "Cadlys Rankor"],
    aegean: ["Bytcon Krypto"],
    cobalt: ["Laivan Ferroo", "The Jagerman", "Necron Exmort", "Iderra"],
    navy: ["Divino Nikola", "Rypite Koldan", "Occeus Coliad", "Dexous"],
    midnight: ["Pramen Kasazh"],
    amethyst: ["Cretas Mglina"],
    jam: [
        "Gingou Disone",
        "Keiksi Ezlilu",
        "Nezrui Rigida",
        "Seinru Narako",
        "Tazsia Poemme",
        "Fortmistress Deadlock",
        "Endari Vernir",
        "Sestro Enthal",
        "Clarud Enthal",
        "Vilcus Cendum",
    ],
    aubergine: ["Edolon Vryche", "Pozzol Broyer", "Neilna Uldiaz"],
    magenta: ["Calder Kerian", "Caesar Consceleratus Persolus"],
    byzantine: ["Oricka Rourst", "Murrit Turkin", "Acerigger Switchem"],
};
